<?php
define('IMAGE_ORIGIN_UPLOAD_PATH','/data/wwwroot/default/weixin/public/tempImages/');
define('IMAGE_UPLOAD_PATH','/data/wwwroot/default/weixin/public/images/');
define('IMAGE_STORE_PATH','http://wechat.qiancs.cn/weixin/public/images/');
define('PRO_CONFIG_1','选项');
define('PRO_CONFIG_2','其他');
define('PRO_CONFIG_3','配菜');
//配置上传图片的路径
//define('IMAGE_UPLOAD_PATH','../uploadImages/');
